### ISSUE TITLE
About the schedule of releasing code

### ISSUE THREAD

**Issue by sh-jj** [trishullab/cosmos#1]
Thanks for sharing such interesting work! 
Is there any new schedule for releasing the code?

**Comment by atharvas** [comment]
Oh shoot! Sorry! I've been pushing back code cleanup because of rebuttal season. I'll work on this next week. Expect a release before Friday, 2nd December. O/w happy to share the private repo. Email/DM me! Keeping this issue open until then!

**Comment by atharvas** [comment]
Update to the release schedule! We'll be doing a full release around mid January. Terribly sorry about the delays.

**Comment by Skywuuuu** [comment]
Hi, is there any new update for releasing the code?
